### PR TITLE
Merge upstream changes from forked repo

### PR DESCRIPTION
**Pull request by Julesssss**
Simply merges the latest upstream changes, must be done via a PR as `master` is protected. Master should now be aligned with the [forked repo](https://github.com/react-native-clipboard/clipboard). 

Fixes: https://github.com/Expensify/Expensify/issues/186596

### CODE REVIEW

**Review by Dal-Papa — DISMISSED** [review]
LGTM

**Comment by parasharrajat** [comment]
@Dal-Papa Please merge it and I can submit my PR. Thanks.

**Comment by Dal-Papa** [comment]
@parasharrajat : We can't merge as there are some unsigned commits. @Julesssss is taking care of this.

**Comment by Julesssss** [comment]
Alright, it was [pretty simple](https://gist.github.com/mattrobertsky/2072b0a1ab81e824a6a5d38240e20b46) to resign a single commit. Ready for another review @Dal-Papa

**Review by Dal-Papa — APPROVED** [review]
Looks even better to me 😄

**Pull request merged**
